# Generated by Django 4.1.1 on 2024-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_movie_options_rename_title_movie_title_orig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_cz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
