# Generated by Django 4.1.1 on 2024-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_movie_length_movie_title_cz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, to='viewer.country'),
        ),
    ]
